language: node_js

sudo: false

node_js:
  - 8
  - 10
  - 12

cache: npm

script:
  - npm run test:prod

after_success:
  - npm run build
  - npm run report-coverage
  - |
    if [[ "$(node --version)" == v10.* && "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      npm run deploy-docs;
    fi
  - |
    if [[ "$(node --version)" == v10.* && "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      npm run semantic-release;
    fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
